# Generated by Django 2.2.15 on 2020-08-17 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0034_auto_20200512_1431'),
        ('signalapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signaldocbase',
            name='chart_html',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.GroupProfile')),
            ],
        ),
        migrations.AddField(
            model_name='signaldocbase',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='signalapi.Collection'),
        ),
    ]
