# Generated by Django 2.2.15 on 2020-08-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signalapi', '0002_auto_20200817_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
