# Generated by Django 2.2.15 on 2020-08-15 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_auto_20200814_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hierarchicalkeyword',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='hierarchicalkeyword',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
    ]
